# Generated by Django 5.2.13 on 2026-04-14 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🔬", max_length=50)),
                (
                    "model_filename",
                    models.CharField(
                        help_text="Filename of the .h5 model in ml_models/",
                        max_length=200,
                    ),
                ),
                ("image_width", models.IntegerField(default=224)),
                ("image_height", models.IntegerField(default=224)),
                (
                    "classes_json",
                    models.TextField(help_text="JSON array of class names"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="diagnoses/%Y/%m/%d/")),
                ("predicted_class", models.CharField(max_length=100)),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence percentage (0-100)"),
                ),
                (
                    "all_predictions_json",
                    models.TextField(
                        default="{}",
                        help_text="JSON object mapping class names to confidence percentages",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="diagnosis.diagnosticmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
